#!/usr/local/bin/python

# Script:  dump2xyz.py
# Purpose: convert a LAMMPS dump file to XYZ format
# Syntax:  dump2xyz.py dumpfile Nid Ntype Nx Ny Nz xyzfile
#          dumpfile = LAMMPS dump file in native LAMMPS format
#          Nid,Ntype,Nx,Ny,Nz = columns #s for ID,type,x,y,z
#                               (usually 1,2,3,4,5)
#          xyzfile = new XYZ file
# Author:  Steve Plimpton (Sandia), sjplimp at sandia.gov

import sys,os
from numpy import *
#path = os.environ["LAMMPS_PYTHON_TOOLS"]
#sys.path.append(path)

if len(sys.argv) < 13:
  raise StandardError, "Syntax: pyWallSin.py xlo xhi ylo yhi z0 A P n0 Dt Dn N outputFiles"

xlo = float(sys.argv[1])
xhi = float(sys.argv[2])
ylo = float(sys.argv[3])
yhi = float(sys.argv[4])
z0 = float(sys.argv[5])
A = float(sys.argv[6])
P = float (sys.argv[7])
n0 = int(sys.argv[8])
Dt = float(sys.argv[9])
Dn = int (sys.argv[10])
N =  int (sys.argv[11])
outputfile = sys.argv[12]

n = arange(0, N,  Dn)
argum= n*Dt*2*math.pi/P
z=z0+A*sin(argum)

for indx in range(len(n)):    
    vtkFile = outputfile+str(indx).zfill(10)+".vtk"
    fs = open(vtkFile,"w")  
    print "Writing %s" % vtkFile
    print >>fs,"# vtk DataFile Version 3.0"
    print >>fs,"Generated by Diego"
    print >>fs,"ASCII"
    print >>fs,"DATASET RECTILINEAR_GRID"
    print >>fs,"DIMENSIONS" , 2, 2, 1
    print >>fs, "X_COORDINATES" ,  2,  "double"
    print >>fs, xlo,  xhi
    print >>fs, "Y_COORDINATES" ,  2,  "double"
    print >>fs, ylo,  yhi
    print >>fs, "Z_COORDINATES" ,  1,  "double"
    print >>fs, z[indx]
fs.close()
